"""
aaizaql.security.audit
──────────────────────
AuditLogger: structured, append-only log of every query and security event.

Writes to a JSONL file (one JSON object per line) when audit_log_file is set.
When no file is configured, events are emitted at DEBUG level via structlog
only — the rest of the pipeline is never blocked.

Author : Ibrahim
Date   : 2024-01-01
Version: 1.0.0
"""

import json
import time
from pathlib import Path
from typing import Any

import structlog

logger = structlog.get_logger(__name__)


class AuditLogger:
    """
    Append-only structured audit log.

    Each record is a JSON object written to the configured JSONL file.
    When no file is configured, events are logged at DEBUG level only.
    File writes are always per-record (no persistent file handle) so the
    log is safe across process restarts and multi-process deployments.
    """

    def __init__(self, log_file: str | None = None) -> None:
        """
        Initialise the audit logger.

        Creates the parent directory for the log file if it does not exist.

        Parameters
        ----------
        log_file : str | None
            Absolute or relative path to the JSONL audit log file.
            Pass None to disable file writing (structlog DEBUG only).
        """
        self._path: Path | None = Path(log_file) if log_file else None
        if self._path:
            self._path.parent.mkdir(parents=True, exist_ok=True)
            logger.info("audit.logger_ready", path=str(self._path))

    def log_query(
        self,
        user_id: str,
        session_id: str,
        question: str,
        sql: str,
        rows: int,
        execution_ms: int,
        was_corrected: bool = False,
    ) -> None:
        """
        Record a completed query execution.

        Parameters
        ----------
        user_id      : str   Identifier of the user who issued the query.
        session_id   : str   Current conversation session identifier.
        question     : str   Original natural-language question.
        sql          : str   The SQL that was executed.
        rows         : int   Number of rows returned.
        execution_ms : int   Wall-clock execution time in milliseconds.
        was_corrected: bool  True if the self-correction loop was triggered.
        """
        self._write(
            event="query",
            user_id=user_id,
            session_id=session_id,
            question=question,
            sql=sql,
            rows=rows,
            execution_ms=execution_ms,
            was_corrected=was_corrected,
        )

    def log_security_event(
        self,
        event_type: str,
        detail: str,
        user_id: str = "",
        sql: str = "",
    ) -> None:
        """
        Record a security violation or suspicious activity.

        Parameters
        ----------
        event_type : str   Short label for the event (e.g. 'injection', 'blocked').
        detail     : str   Human-readable description of what was detected.
        user_id    : str   Identifier of the user involved (empty if unknown).
        sql        : str   The SQL string involved, if any.
        """
        self._write(
            event=f"security.{event_type}",
            user_id=user_id,
            detail=detail,
            sql=sql,
        )

    def log_correction(
        self,
        original_sql: str,
        error: str,
        corrected_sql: str,
    ) -> None:
        """
        Record a self-correction cycle outcome.

        Parameters
        ----------
        original_sql  : str  The SQL that caused the error.
        error         : str  The error message returned by the database.
        corrected_sql : str  The replacement SQL generated by the corrector.
        """
        self._write(
            event="self_correction",
            original_sql=original_sql,
            error=error,
            corrected_sql=corrected_sql,
        )

    # ── Private ───────────────────────────────────────────────────────────────

    def _write(self, **fields: Any) -> None:
        """
        Append a single audit record to the log file.

        Always emits via structlog at DEBUG level.  File write failures are
        logged as warnings but never propagate — audit must not block queries.

        Parameters
        ----------
        **fields : Any
            Arbitrary key-value pairs merged into the audit record alongside
            a Unix-epoch timestamp (``ts``).
        """
        record: dict[str, Any] = {"ts": time.time(), **fields}
        logger.debug("audit.event", **fields)
        if self._path:
            try:
                with self._path.open("a", encoding="utf-8") as fh:
                    fh.write(json.dumps(record, default=str) + "\n")
            except OSError as exc:
                logger.warning("audit.write_failed", detail=str(exc))
