"""
aaizaql.security.validator
─────────────────────────
SQLValidator: the security gate that every SQL statement must pass before
execution.  No SQL ever runs without passing through here.

Three checks (in order):
1. Prompt injection detection — scan the *question* for manipulation attempts.
2. Operation whitelist — only SELECT / WITH are allowed by default.
3. Dialect-aware structural parse — uses sqlglot to catch malformed SQL and
   detect dangerous statement types that could be disguised with comments.

Author : Ibrahim
Date   : 2024-01-01
Version: 1.0.0
"""

import re

import sqlglot
import structlog

from aaizaql.core.config import Settings
from aaizaql.core.exceptions import PromptInjectionDetected, SecurityException

logger = structlog.get_logger(__name__)

# ── Prompt injection signatures ───────────────────────────────────────────────
# Common patterns used to override system instructions.
_INJECTION_PATTERNS: list[re.Pattern[str]] = [
    re.compile(p, re.IGNORECASE)
    for p in [
        r"ignore\s+(all\s+)?previous\s+instructions",
        r"disregard\s+",
        r"forget\s+your\s+(instructions|rules|system\s+prompt)",
        r"you\s+are\s+now\s+(a\s+)?(?:different|new|evil|unrestricted)",
        r"override\s+(your\s+)?(instructions|rules|constraints)",
        r"act\s+as\s+(?:if\s+you\s+(?:have\s+no|are\s+without)\s+restrictions)",
        r"do\s+not\s+follow\s+your\s+(rules|guidelines)",
        r"system\s*:\s*you\s+are",
        r"<\s*system\s*>",
        r"###\s*new\s+instructions",
        r"reveal\s+your\s+(system\s+)?prompt",
        r"print\s+your\s+(system\s+)?prompt",
        r"show\s+me\s+your\s+(system\s+)?prompt",
    ]
]

# Dangerous SQL keywords that should never appear in a SELECT-only context.
_DANGEROUS_KEYWORDS: frozenset[str] = frozenset(
    [
        "INSERT",
        "UPDATE",
        "DELETE",
        "DROP",
        "TRUNCATE",
        "ALTER",
        "CREATE",
        "REPLACE",
        "MERGE",
        "EXEC",
        "EXECUTE",
        "CALL",
        "GRANT",
        "REVOKE",
        "LOAD",
        "IMPORT",
        "COPY",
        "ATTACH",
        "DETACH",
    ]
)

# AST node types that are safe to execute.
_ALLOWED_AST_TYPES: frozenset[str] = frozenset({"SELECT", "UNION", "INTERSECT", "EXCEPT", "WITH"})


class SQLValidator:
    """
    Security gate for all SQL generated by the LLM.

    Runs three sequential checks: keyword scan, operation whitelist, and
    sqlglot structural parse.  All checks must pass or a SecurityException
    is raised.

    Usage::

        validator = SQLValidator(settings)
        validator.check_question(question)  # raises PromptInjectionDetected
        validator.validate(sql)             # raises SecurityException if unsafe
    """

    def __init__(self, settings: Settings) -> None:
        """
        Initialise the validator from application settings.

        Parameters
        ----------
        settings : Settings
            Application settings containing allowed SQL operations and
            injection detection toggle.
        """
        self._allowed_ops: frozenset[str] = frozenset(
            op.upper() for op in settings.allowed_sql_operations
        )
        self._injection_check: bool = settings.enable_injection_detection

    # ── Public API ────────────────────────────────────────────────────────────

    def validate(self, sql: str) -> None:
        """
        Run the full security validation pipeline on a SQL string.

        Checks are executed in order: dangerous keyword scan → operation
        whitelist → sqlglot structural parse.  Stops at the first failure.

        Parameters
        ----------
        sql : str
            The SQL statement to validate.

        Raises
        ------
        SecurityException
            If the SQL is empty, contains disallowed keywords, uses a
            forbidden operation, or fails structural parsing.
        """
        stripped = sql.strip()

        if not stripped:
            raise SecurityException("Empty SQL statement received.", sql=sql)

        self._check_dangerous_keywords(stripped)
        self._check_allowed_operations(stripped)
        self._check_with_sqlglot(stripped)

        logger.debug("validator.passed", sql_preview=stripped[:60])

    def check_question(self, question: str) -> None:
        """
        Scan a natural-language question for prompt injection attempts.

        Call this before SQL generation so injections never reach the LLM.
        Does nothing when injection detection is disabled in settings.

        Parameters
        ----------
        question : str
            The raw user question to scan.

        Raises
        ------
        PromptInjectionDetected
            If any known injection pattern matches the question text.
        """
        if not self._injection_check:
            return
        for pattern in _INJECTION_PATTERNS:
            if pattern.search(question):
                logger.warning(
                    "validator.injection_detected",
                    pattern=pattern.pattern,
                    question=question[:80],
                )
                raise PromptInjectionDetected(
                    reason=f"Prompt injection pattern detected: '{pattern.pattern}'",
                    sql="",
                )

    # ── Private checks ────────────────────────────────────────────────────────

    def _check_dangerous_keywords(self, sql: str) -> None:
        """
        Keyword scan to catch obviously dangerous statements before parsing.

        Normalises whitespace and strips comments first to prevent bypass via
        comment obfuscation.  Uses word-boundary tokenisation so 'SELECTED'
        does not trigger 'DELETE'.

        Parameters
        ----------
        sql : str
            Stripped SQL string (no leading/trailing whitespace).

        Raises
        ------
        SecurityException
            If any token in the SQL matches a forbidden keyword.
        """
        normalised = self._strip_comments(sql).upper()
        tokens: set[str] = set(re.findall(r"\b[A-Z_]+\b", normalised))
        bad = tokens & _DANGEROUS_KEYWORDS
        if bad:
            raise SecurityException(
                f"Disallowed SQL keyword(s) detected: {sorted(bad)}",
                sql=sql,
            )

    def _check_allowed_operations(self, sql: str) -> None:
        """
        Ensure the first meaningful keyword is in the configured allowlist.

        Handles CTEs (WITH ... AS (...) SELECT ...) by checking the first
        token after stripping comments and whitespace.

        Parameters
        ----------
        sql : str
            Stripped SQL string (no leading/trailing whitespace).

        Raises
        ------
        SecurityException
            If the first keyword is not in the allowed operations set.
        """
        normalised = self._strip_comments(sql).strip().upper()
        first_keyword = re.split(r"\s+", normalised)[0] if normalised else ""

        if first_keyword not in self._allowed_ops:
            raise SecurityException(
                f"SQL operation '{first_keyword}' is not permitted. "
                f"Allowed: {sorted(self._allowed_ops)}",
                sql=sql,
            )

    def _check_with_sqlglot(self, sql: str) -> None:
        """
        Parse the SQL with sqlglot to catch structural and disguised threats.

        Catches stacked queries (SELECT 1; DROP TABLE users), unparse-able
        SQL, and AST node types that are not on the safe list.

        Parameters
        ----------
        sql : str
            Stripped SQL string (no leading/trailing whitespace).

        Raises
        ------
        SecurityException
            If the SQL cannot be parsed, resolves to zero or multiple
            statements, or produces a disallowed AST node type.
        """
        try:
            statements = sqlglot.parse(sql)
        except Exception:
            raise SecurityException(
                "SQL could not be parsed — it may be malformed or use an " "unsupported dialect.",
                sql=sql,
            ) from None

        if not statements:
            raise SecurityException("SQL parsed to zero statements.", sql=sql)

        if len(statements) > 1:
            raise SecurityException(
                f"Multiple SQL statements detected ({len(statements)}). "
                "Only a single SELECT is permitted.",
                sql=sql,
            )

        stmt = statements[0]
        if stmt is None:
            raise SecurityException("SQL parsed to a null statement.", sql=sql)

        stmt_type = type(stmt).__name__.upper()
        if stmt_type not in _ALLOWED_AST_TYPES:
            raise SecurityException(
                f"Parsed statement type '{stmt_type}' is not allowed.",
                sql=sql,
            )

    @staticmethod
    def _strip_comments(sql: str) -> str:
        """
        Remove SQL comments from a string.

        Handles both block comments (/* ... */) and line comments (-- ...).

        Parameters
        ----------
        sql : str
            Raw SQL string that may contain comments.

        Returns
        -------
        str
            SQL string with all comments replaced by a single space.
        """
        sql = re.sub(r"/\*.*?\*/", " ", sql, flags=re.DOTALL)
        sql = re.sub(r"--[^\n]*", " ", sql)
        return sql
